# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Adam/Desktop/ECE 3829/Lab 3/lab_3/lab_3.srcs/sources_1/ip/clk_mmcm_wiz/clk_mmcm_wiz.xci
# IP: The module: 'clk_mmcm_wiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Adam/Desktop/ECE 3829/Lab 3/lab_3/lab_3.gen/sources_1/ip/clk_mmcm_wiz/clk_mmcm_wiz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm_wiz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Adam/Desktop/ECE 3829/Lab 3/lab_3/lab_3.gen/sources_1/ip/clk_mmcm_wiz/clk_mmcm_wiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Adam/Desktop/ECE 3829/Lab 3/lab_3/lab_3.gen/sources_1/ip/clk_mmcm_wiz/clk_mmcm_wiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Adam/Desktop/ECE 3829/Lab 3/lab_3/lab_3.srcs/sources_1/ip/clk_mmcm_wiz/clk_mmcm_wiz.xci
# IP: The module: 'clk_mmcm_wiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Adam/Desktop/ECE 3829/Lab 3/lab_3/lab_3.gen/sources_1/ip/clk_mmcm_wiz/clk_mmcm_wiz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Adam/Desktop/ECE 3829/Lab 3/lab_3/lab_3.gen/sources_1/ip/clk_mmcm_wiz/clk_mmcm_wiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Adam/Desktop/ECE 3829/Lab 3/lab_3/lab_3.gen/sources_1/ip/clk_mmcm_wiz/clk_mmcm_wiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm_wiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
